### PR TITLE
Rename WebRTCRoomModel `id` attr into `room_id`

### PR DESCRIPTION
**Pull request by martinRenou**
Having an `id` attribute overwrite the one from the base widget class (at least for xwebrtc)

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Note: `id` is also a special property in backbone.

The thing is that upon `comm_open`, `xwidgets` will use the comm id and not the overwritten `id` property...

**Comment by maartenbreddels** [comment]
lgtm

**Comment by SylvainCorlay** [comment]
tenor

**Comment by maartenbreddels** [comment]
@martinRenou push it! :)

**Comment by martinRenou** [comment]
Fus Ro Dah !!

**Pull request merged**
