### PR TITLE
Apply linting throughout project

### PR DESCRIPTION
**Pull request by gjmooney**
Applies Ruff and Prettier linting throughout project.

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Nice!
Which tools did you use?
Because I want to have pre-commit and CI run these so that it stays tidy (similar to https://github.com/widgetti/ipyreact/pull/51/files)

**Comment by gjmooney** [comment]
> Nice! Which tools did you use? Because I want to have pre-commit and CI run these so that it stays tidy (similar to https://github.com/widgetti/ipyreact/pull/51/files)

I used the VSCode versions of Ruff and Prettier.

**Comment by maartenbreddels** [comment]
Would you like to add a similar setup of what @mariobuikhuizen did in https://github.com/widgetti/ipyreact/pull/51 to this PR or would you rather have me do this?

**Comment by gjmooney** [comment]
> Would you like to add a similar setup of what @mariobuikhuizen did in [widgetti/ipyreact#51](https://github.com/widgetti/ipyreact/pull/51) to this PR or would you rather have me do this?

Yea I can do that

**Review by martinRenou — APPROVED** [review]
Thanks!

**Comment by martinRenou** [comment]
@maartenbreddels Is it ok to merge?

**Pull request merged**
