### PR TITLE
Add minimal current-state binder of dev setup

### PR DESCRIPTION
**Pull request by bollwyvl**
This is a minimal binder setup for a "dev" install of the extension, running in notebook Classic and built with `npm`.

While not quite as reliable or quick as one pinned to the lastest, say conda-forge release, it does have the advantage of putting some eyeballs on master code... or even PRs. For example, here's this PR:
https://mybinder.org/v2/gh/bollwyvl/ipywebrtc/binder?filepath=docs%2Fsource%2FLocal%20media.ipynb

I was going to look at any updates needed to get this working in jupyterlab beta, but wanted a stable baseline first, and something i could demo quickly.

Happy to close this in favor of a "production" binder setup, but figured this might make collaboration a bit easier!

Some more background: I saw this demoed at JupyterCon, and was really impressed. There's a ton of stuff available from the HTML5 APIs that we've barely scratched: [webusb](https://github.com/mrdoob/daydream-controller.js/), or [geolocation](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation). We did [a talk](https://github.com/tonyfast/powersoften), and used ipywebrtc and even built our own labextension for the then-current version (because of some other extension work, sorry i didn't PR then). 

People are pretty blown away when you turn your laptop around, and they are seeing themselves, as a group, up on the projector. 

Anyhow, looking forward to more cool stuff here!

### CODE REVIEW

**Comment by bollwyvl** [comment]
So are you suggesting a pip-only approach? I was hoping to get to [back to running](https://www.npmjs.com/package/jupyterlab-webrtc) this in JupyterLab soon, and don't know if there's a node in the `repo2docker` baseline. Also other sweet demos, e.g. skimage, would be better suited to conda.

Sheets looks great, by the way!

**Comment by bollwyvl** [comment]
By the by, just checked and there is a node in the repo2binder, but it's pretty old, 6.11.4. Still a bit more comfortable provisioning a predictable version...

**Comment by bollwyvl** [comment]
Thinking about it some more, I guess my resistance to `git+https...master...` is that then the file is not useful for local development or CI, which I would expect an `environment.yml` to be. Also, we already have a checkout of the code! An option would be to move the binder-specific stuff into a [`.binder` directory](https://github.com/jupyter/repo2docker/pull/83), such that you'd always be running against a known-good version (hopefully!).

However, I still _really_ like being able to fire up a PR (or any other commitish) on a repo and load that in a binder. Of course, you'd be able to pop into the binder, uninstall the lib and `pip install -e .`, but that seems a bit awkward.

**Comment by maartenbreddels** [comment]
Forgot about it, but LGTM! Thanks!

**Comment by bollwyvl** [comment]
Hooray! Looking forward to playing with this.

**Pull request merged**
