### PR TITLE
Support Jupyter lab 2 and 3

### PR DESCRIPTION
**Pull request by maartenbreddels**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Replaces #74
Depends on https://github.com/jupyterlab/jupyterlab/pull/9636

**Comment by wolfv** [comment]
@maartenbreddels do you have an estimate on how hard it will be to make this work in jlab 3?

**Comment by martinRenou** [comment]
I can update it if you guys want

**Comment by maartenbreddels** [comment]
This should work if https://github.com/jupyterlab/jupyterlab/pull/9636 is released.

**Pull request merged**
